[[constraint]]
  name = "github.com/qiangxue/fasthttp-routing"
  branch = "master"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20160617.0.0"

[[constraint]]
  name = "github.com/bearbin/go-age"
  branch = "master"